# Generated by Django 5.1.7 on 2025-03-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_balance',
        ),
    ]
