# Generated by Django 5.1.7 on 2025-03-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_account_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='Company',
            new_name='company',
        ),
    ]
