# Generated by Django 5.1.7 on 2025-03-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_rename_company_kyc_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='signature',
        ),
    ]
