# Generated by Django 5.1.7 on 2025-03-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_user_company_user_date_of_birth_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frist_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Frist Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
