# Generated by Django 5.1.7 on 2025-03-24 01:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_user_frist_name_alter_user_first_name_delete_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
