# Generated by Django 5.1.7 on 2025-03-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default=1, max_length=255, verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=3, max_length=50, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
