# Generated by Django 5.1.7 on 2025-03-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_user_company_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
    ]
